### ISSUE TITLE
project need upgrade to v4.7.2

### ISSUE THREAD

**Issue by uragan1987** [ReClassNET/ReClass.NET-DotNetInspectorPlugin#1]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3274: The primary reference "U:\andi\Projekte\hacking\csharp\ReClass.NET-DotNetInspectorPlugin\bin\Debug\x64\ReClass.NET.exe" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".

project need upgrade to v4.7.2

**Comment by uragan1987** [comment]
after upgrade to v4.7.2
and fix 1 error at ReClassNetDataReader.cs

line5: //using System.Runtime.InteropServices;
line66:             System.Runtime.InteropServices.Marshal.Copy(temp, 0, buffer, bytesRequested);

still cant see plugin at File>Plugins

**Comment by KN4CK3R** [comment]
I pushed the version and fixed the compilation error. Afterwards just copy the dll in the `Plugins` folder where the ReClass.NET.exe is.

A note: I never finished this plugin so it's in alpha stadium but works:
![grafik](https://user-images.githubusercontent.com/1666336/103650082-c45f4f00-4f5f-11eb-8463-75a33840986f.png)

**Comment by uragan1987** [comment]
im focused on x86 version
1. after compile x86 version then DLL is inside "ReClass.NET-DotNetInspectorPlugin\bin\Debug" , so x86 Folder just has ReClass.NET.exe and dunno why you need it there, i cant run it 
@x64 its inside bin\Debug\x64\ Folder, looks good

2. After compile, i get this screen,

![grafik](https://user-images.githubusercontent.com/13498010/103670076-6b041980-4f79-11eb-804e-d75b75d38ff7.png)
just wanna tell, write somewhere about Plugins Folder, there is nothing :)

now i see it
![grafik](https://user-images.githubusercontent.com/13498010/103670303-b0284b80-4f79-11eb-9c23-215c992070f5.png)
